# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/blackDZS"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:1980694906@qq.com"

[social.params]
icon = "brand-email"

[[social]]
identifier = "zhihu"
name = "Zhihu"
url = "https://www.zhihu.com/people/di-zhen-sheng"

[social.params]
icon = "brand-zhihu"